### ISSUE TITLE
Dowonload Leaked password list // Sorry, the link has expired

### ISSUE THREAD

**Issue by StefanSa** [improsec/Get-bADpasswords#3]
Hi there,
First of all thank you for the very interesting project.
I get the following error message from the Sharepoint.

`Sorry, the link has expired`

Can someone reload the data to the sharepoint?
thx

**Comment by VirtualPuppet** [comment]
Hello StefanSa, and sorry for the late reply.

The pwned-passwords.bin file was previous updated, but I've just updated it to the Troy Hunt v6 list. Please check the description for further information :)
